spring.application.name=hardwarehub

# ==========================
#   MYSQL EN DOCKER
# ==========================

# Conectar con el MySQL que se levanta en docker-compose (mapea puerto 3306)
spring.datasource.url=jdbc:mysql://localhost:3306/hardwarehub_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=hwuser
spring.datasource.password=hwpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Permitir que se ejecute data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

# Logging SQL
logging.level.org.hibernate.SQL=debug
